### ISSUE TITLE
Chapter 1 - Singleton Pattern Samples

### ISSUE THREAD

**Issue by artlantis** [Apress/design-patterns-csharp-2e#1]
Hi,
I don't know whether you did consciously but you had forgotten to add Singleton Pattern sample that available in chapter one. Could you please check? 
Also, in the first edition, the folder names was the same with design pattern name.

**Comment by Vaskaran** [comment]
Thanks. Yes, Ch-1 and Ch-6 were placed under ch-12 and ch-5 repectively. It is corrected now.
